server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: Product
  data:
    mongodb:
      uri: mongodb://localhost:27017/eshoponsteroidsproductservice
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 0

# custom properties for our message bus
message-bus:
  exchange-name: 'eshoponsteroids'  # name of the exchange
  queue-name: 'new-order' # name of the queue
  routing-key: 'new-order'  # used to route messages from the exchange to the specified queue

springdoc:
  api-docs:
    version: openapi_3_0
    path: '/api/v1/product/api-docs'
  swagger-ui:
    enabled: true
    path: '/api/v1/product/swagger-ui.html'
