server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: product
  devtools:
    restart:
      additional-paths: src/main
  data:
    mongodb:
      uri: ${PRODUCT_DB_URL}
  zipkin:
    base-url: ${ZIPKIN_BASE}
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: ${RABBITMQ_BASE}
  cloud:
    consul:
      host: ${DISCOVERY_SERVER_HOST} # Consul server host
      port: 8500 # Consul server port
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        serviceName: ${spring.application.name}

grpc:
  server:
    port: 0

# custom properties for our message bus
message-bus:
  exchange-name: 'eshoponsteroids'  # name of the exchange
  queue-name: 'new-order' # name of the queue
  routing-key: 'new-order'  # used to route messages from the exchange to the specified queue

management:
  endpoint:
    metrics:
      enabled: true # enable metrics endpoint
    prometheus:
      enabled: true # enable prometheus endpoint
  endpoints:
    web:
      exposure:
        include: '*' # expose all endpoints
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true # enable prometheus metrics exporter

springdoc:
  api-docs:
    version: openapi_3_0
    path: '/api/v1/product/api-docs'
  swagger-ui:
    enabled: true
    path: '/api/v1/product/swagger-ui.html'
