server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: Product
  data:
    mongodb:
      uri: mongodb://localhost:27017/eshoponsteroidsproductservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 0
