server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: Order
  datasource:
    url: 'jdbc:postgresql://localhost:5432/eshoponsteroidsorderservice'
    username: 'postgres'
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false # disable logging of sql statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
