eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
    port: 8080

rsa:
  public-key: classpath:certs/public.pem

# Routes
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: Product
          uri: lb://product
          predicates:
            - Path=/api/v*/product/**

        - id: Order
          uri: lb://order
          predicates:
            - Path=/api/v*/order/**

        - id: Identity
          uri: lb://identity
          predicates:
            - Path=/api/v*/identity/{segment}/**

        - id: Cart
          uri: lb://cart
          predicates:
            - Path=/api/v*/cart/**

        - id: DiscoveryServer
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/   # /eureka/web -> /

        - id: DiscoveryServerStaticResources
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0