server:
  port: 8080

rsa:
  public-key: classpath:certs/public.pem

# Routes
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      additional-paths: src/main
  cloud:
    gateway:
      routes:
        - id: Product
          uri: ${PRODUCT_MICROSERVICE_URL}
          predicates:
            - Path=/api/v*/product/**

        - id: Order
          uri: ${ORDER_MICROSERVICE_URL}
          predicates:
            - Path=/api/v*/order/**

        - id: Identity
          uri: ${IDENTITY_MICROSERVICE_URL}
          predicates:
            - Path=/api/v*/identity/{segment}/**

        - id: Cart
          uri: ${CART_MICROSERVICE_URL}
          predicates:
            - Path=/api/v*/cart/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
  zipkin:
    base-url: ${ZIPKIN_BASE}
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
