eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_BASE}/eureka/

server:
    port: 8080

rsa:
  public-key: classpath:certs/public.pem

# Routes
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: Product
          uri: lb://product
          predicates:
            - Path=/api/v*/product/**

        - id: Order
          uri: lb://order
          predicates:
            - Path=/api/v*/order/**

        - id: Identity
          uri: lb://identity
          predicates:
            - Path=/api/v*/identity/{segment}/**

        - id: Cart
          uri: lb://cart
          predicates:
            - Path=/api/v*/cart/**

        - id: DiscoveryServer
          uri: ${DISCOVERY_SERVER_BASE}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/   # /eureka/web -> /

        - id: DiscoveryServerStaticResources
          uri: ${DISCOVERY_SERVER_BASE}
          predicates:
            - Path=/eureka/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
  zipkin:
    base-url: ${ZIPKIN_BASE}
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
