global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: 'http://host.docker.internal:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: instance
