apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: eshoponsteroids
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'spring'
        metrics_path: '/actuator/prometheus'
        consul_sd_configs:
          - server: 'http://discovery-server:8500'
        relabel_configs:
          - source_labels: [__meta_consul_service]
            target_label: instance
