server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: Identity
  datasource:
    url: 'jdbc:postgresql://localhost:5432/eshoponsteroidsidentitymicroservice'
    username: 'postgres'
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # disable logging of sql statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    version: openapi_3_0
    path: '/api/v1/identity/api-docs'
  swagger-ui:
    enabled: true
    path: '/api/v1/identity/swagger-ui.html'
