server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: Identity
  datasource:
    url: 'jdbc:postgresql://localhost:5432/eshoponsteroidsidentityservice'
    username: 'postgres'
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # disable logging of sql statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
