apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: eshoponsteroids
spec:
  type: LoadBalancer  # request a load balancer from the cloud provider
  ports:
    - name: api-gateway
      port: 8080  # port used to access the service from outside the cluster
      targetPort: 8080  # port exposed by the deployment targeted by this service
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
  selector:
    network: public   # tell this service to target all pods with the label network: public
    