apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-db
  namespace: eshoponsteroids
spec:
  selector:
    matchLabels:
      app: cart-db  # tell this deployment to target the pods with the label app: cart-db
  replicas: 1 # only one instance of the pod
  template: # template for the pods created by this deployment
    metadata:
      labels:
        app: cart-db
    spec:
      containers:
        - name: cart-db
          image: redis:7.2.1
          ports:  # expose the port 6379
            - containerPort: 6379
          volumeMounts: # mount the volume to the container
            - name: cart-db
              mountPath: /data
          readinessProbe: # check if the container is ready to accept traffic
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: cart-db
          persistentVolumeClaim:
            claimName: cart-db-pvc

---

# service to expose deployment
apiVersion: v1
kind: Service
metadata:
  name: cart-db
  namespace: eshoponsteroids
spec:
  type: ClusterIP # expose the service inside the cluster
  selector:
    app: cart-db    # tell this service to target the pods with the label app: cart-db
  ports:
    - port: 6379  # port exposed by the service
      targetPort: 6379    # port exposed by the container
