apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart # name of the deployment
  namespace: eshoponsteroids
spec:
  selector:
    matchLabels:
      app: cart # tell this deployment to target the pods with the label app: cart
  template:  # template for the pods created by this deployment
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: badasstechie/eshoponsteroids-cart:latest  # image to be pulled from Docker Hub
          imagePullPolicy: Always   # always pull the image from Docker Hub even if it exists locally
          ports:
            - containerPort: 8081 # port exposed by the container
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            limits:
              cpu: "1"  # limit the CPU cores to 1
            requests:
              cpu: "400m"  # request at least 0.4 CPU cores

---

# service to expose deployment
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: eshoponsteroids
spec:
  type: ClusterIP # expose the service inside the cluster
  ports:
      - port: 8081  # port exposed by the service
        targetPort: 8081  # port exposed by the container
  selector:
    app: cart # tell this service to target the pods with the label app: cart

---

# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata: 
  name: cart
  namespace: eshoponsteroids
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: cart  # scale the cart deployment
  minReplicas: 1  # have at least one instance
  maxReplicas: 4   # have at most 4 instances
  metrics: 
    - type: Resource 
      resource: 
        name: cpu 
        target: 
          type : Utilization 
          averageUtilization: 75  # scale to achieve an average CPU utilization of 75%
