apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: eshoponsteroids
spec:
  selector:
    matchLabels:
      app: discovery-server   # tell this deployment to target the pods with the label app: discovery-server
  replicas: 1 # only one instance of the pod
  template: # template for the pods created by this deployment
    metadata:
      labels:
        app: discovery-server
        network: public
    spec:
      containers:
        - name: discovery-server
          image: hashicorp/consul:1.16
          args:
            - "agent"
            - "-dev"
            - "-client=0.0.0.0"
          ports:  # expose the port 8500
            - containerPort: 8500

---

# service to expose deployment
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: eshoponsteroids
spec:
  type: ClusterIP # expose the service inside the cluster
  selector:
    app: discovery-server # tell this service to target the pods with the label app: discovery-server
  ports:
    - port: 8500  # port exposed by the service
      targetPort: 8500    # port exposed by the container
