apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: eshoponsteroids
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.17
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: eshoponsteroids
spec:
  type: ClusterIP
  ports:
      - port: 9200
        targetPort: 9200
  selector:
    app: elasticsearch
