apiVersion: apps/v1
kind: DaemonSet # a daemonset ensures that all nodes run a copy of a pod
metadata:
  name: fluentd
  namespace: eshoponsteroids
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.16.2-debian-elasticsearch7-1.1
        volumeMounts:
          - name: fluentd-config
            mountPath: /fluentd/etc/fluent.conf
            subPath: fluent.conf
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-configmap
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
