apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order # name of the deployment
  namespace: eshoponsteroids
spec:
  serviceName: order
  selector:
    matchLabels:
      app: order  # tell this deployment to target the pods with the label app: order
  template:  # template for the pods created by this deployment
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: badasstechie/eshoponsteroids-order:latest  # image to be pulled from Docker Hub
          imagePullPolicy: Always   # always pull the image from Docker Hub even if it exists locally
          ports:
            - containerPort: 8083 # port exposed by the container
          envFrom:
            - configMapRef:
                name: env-vars
            - secretRef:
                name: env-secrets
          env:
            - name: SERVER_PORT
              value: "8083" # Override random port with one that is known so that we can expose it
          resources:
            limits:
              cpu: "1"  # limit the CPU usage to 1 cores
            requests:
              cpu: "400m"  # request at least 0.4 CPU cores

---

# service to expose deployment
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: eshoponsteroids
spec:
  type: ClusterIP # expose the service inside the cluster
  ports:
      - port: 8083  # port exposed by the service
        targetPort: 8083  # port exposed by the container
  selector:
    app: order  # tell this service to target the pods with the label app: order

---

# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata: 
  name: order
  namespace: eshoponsteroids
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: order  # scale the order deployment
  minReplicas: 1  # have at least one instance
  maxReplicas: 4   # have at most 4 instances
  metrics: 
    - type: Resource 
      resource: 
        name: cpu 
        target: 
          type : Utilization 
          averageUtilization: 70  # scale to achieve an average CPU utilization of 70%
