apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product # name of the deployment
  namespace: eshoponsteroids
spec:
  serviceName: product
  selector:
    matchLabels:
      app: product  # tell this deployment to target the pods with the label app: product
  template:  # template for the pods created by this deployment
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: badasstechie/eshoponsteroids-product:latest  # image to be pulled from Docker Hub
          imagePullPolicy: Always   # always pull the image from Docker Hub even if it exists locally
          ports:
            - name: http
              containerPort: 8084
            - name: grpc
              containerPort: 9898
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            limits:
              cpu: "750m"  # limit the CPU usage to 0.75 cores
            requests:
              cpu: "300m"  # request at least 0.3 CPU cores

---

# service to expose deployment
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: eshoponsteroids
spec:
  type: ClusterIP # expose the service inside the cluster
  ports:
      - name: http
        port: 8084
        targetPort: 8084
      - name: grpclb
        port: 9898
        targetPort: 9898
  selector:
    app: product  # tell this service to target the pods with the label app: product

---

# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata: 
  name: product
  namespace: eshoponsteroids
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: product  # scale the product deployment
  minReplicas: 1  # have at least one instance
  maxReplicas: 4   # have at most 4 instances
  metrics: 
    - type: Resource 
      resource: 
        name: cpu 
        target: 
          type : Utilization 
          averageUtilization: 70  # scale to achieve an average CPU utilization of 70%
