apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: eshoponsteroids
spec:
  replicas: 1 # have only one instance of the pod
  selector:
    matchLabels:
      app: rabbitmq  # tell this deployment to target the pods with the label app: api-gateway
  template:  # template for the pods created by this deployment
    metadata:
      labels:
        app: rabbitmq
        network: public # label to indicate that this pod should be exposed to the public network
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq:3
          ports:     # ports exposed by the container
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          readinessProbe: # check if the container is ready to accept traffic
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: rabbitmq-data
          emptyDir: {}

---

# service to expose deployment
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: eshoponsteroids
spec:
  type: ClusterIP # expose the service inside the cluster
  selector:
    app: rabbitmq # tell this service to target the pods with the label app: api-gateway
  ports:
    - port: 5672  # port exposed by the service
      targetPort: 5672  # port exposed by the container
