server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  application:
    name: Cart
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
