name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Copy env.example files to dummy .env (required for docker compose)
      run: |
        find . -name env.example -exec bash -c 'cp "$1" "${1%env.example}.env"' _ {} \;

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Images
      run: |
        docker compose build
        docker compose push
