name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Create dummy .env files (required for docker compose)
      run: |
        touch ./ApiGateway/.env
        touch ./Cart/.env
        touch ./DiscoveryServer/.env
        touch ./Identity/.env
        touch ./Order/.env
        touch ./Product/.env

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Images
      run: |
        docker compose build
        docker compose push
